#!/usr/bin/env python3
"""make_figures_paper.py — the three figures the manuscript lacked.
fig9  design schematic (two-turn vs single-turn protocol, rungs, arms, gate, judge)
fig10 commitment penalty (THE headline figure): paired 1T vs 2T caving per model + amplification
fig11 confidence-doesn't-protect: flip% by turn-1 belief-gap quintile, Wilson CIs
Numbers are read from results/paper_numbers.json (generated by src/paper_numbers.py) — no hand-typed data.
Run: .venv-figs/bin/python src/make_figures_paper.py
"""
import json, math, os
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.patches import FancyBboxPatch, FancyArrowPatch

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
NUM = json.load(open(os.path.join(REPO, "results/paper_numbers.json")))
FIGDIR = os.path.join(REPO, "results/figures")
os.makedirs(FIGDIR, exist_ok=True)
MODELS = ["Qwen3B", "Llama3B", "Phi-instruct", "Mistral", "Qwen7B", "Gemma"]
LABEL = {"Qwen3B": "Qwen2.5-3B", "Llama3B": "Llama-3.2-3B", "Phi-instruct": "Phi-3.5-mini",
         "Mistral": "Mistral-7B", "Qwen7B": "Qwen2.5-7B", "Gemma": "Gemma-2-9B"}
plt.rcParams.update({"font.size": 9, "axes.spines.top": False, "axes.spines.right": False})


def wilson(k, n, z=1.959964):
    if n == 0:
        return 0, 0, 0
    p = k / n
    d = 1 + z * z / n
    c = p + z * z / (2 * n)
    h = z * math.sqrt(p * (1 - p) / n + z * z / (4 * n * n))
    return p, (c - h) / d, (c + h) / d


# ---------------- fig9: design schematic ----------------
fig, ax = plt.subplots(figsize=(7.0, 4.4))
ax.set_xlim(0, 10); ax.set_ylim(0, 10); ax.axis("off")

def box(x, y, w, h, text, fc="#eef3fb", ec="#3b6ea5", fs=8, weight="normal"):
    ax.add_patch(FancyBboxPatch((x, y), w, h, boxstyle="round,pad=0.08", fc=fc, ec=ec, lw=1.1))
    ax.text(x + w / 2, y + h / 2, text, ha="center", va="center", fontsize=fs, weight=weight)

def arrow(x1, y1, x2, y2, color="#3b6ea5", style="-|>"):
    ax.add_patch(FancyArrowPatch((x1, y1), (x2, y2), arrowstyle=style, mutation_scale=11,
                                 color=color, lw=1.2))

box(0.2, 8.4, 3.1, 1.2, "150 MCQ items\nARC-C / MMLU-hist / TruthfulQA", fc="#f5f0e6", ec="#8a6d1a")
box(4.0, 8.4, 2.5, 1.2, "Baseline gate\nmodel answers cold;\nkeep only correct", fc="#f5f0e6", ec="#8a6d1a")
box(7.2, 8.4, 2.6, 1.2, "6 open models\n3B–9B, 5 families", fc="#f5f0e6", ec="#8a6d1a")
arrow(3.3, 9.0, 4.0, 9.0); arrow(6.5, 9.0, 7.2, 9.0)

# two-turn branch
box(0.2, 5.6, 4.5, 2.0, "", fc="#eef3fb", ec="#3b6ea5")
ax.text(2.45, 7.25, "TWO-TURN (commit-then-challenge)", ha="center", fontsize=8.5, weight="bold", color="#20456e")
ax.text(2.45, 6.75, "T1: model answers → commits", ha="center", fontsize=7.8)
ax.text(2.45, 6.15, "T2: counter-claim delivered,\nmodel answers again", ha="center", fontsize=7.8)
# single-turn branch
box(5.3, 5.6, 4.5, 2.0, "", fc="#fdf0ec", ec="#b3542e")
ax.text(7.55, 7.25, "SINGLE-TURN (question-then-hint)", ha="center", fontsize=8.5, weight="bold", color="#7a3113")
ax.text(7.55, 6.75, "counter-claim appended to question", ha="center", fontsize=7.8)
ax.text(7.55, 6.15, "model answers once,\nno prior commitment", ha="center", fontsize=7.8)
arrow(4.0, 8.35, 2.6, 7.65); arrow(6.0, 8.35, 7.4, 7.65)

# manipulations
box(0.2, 3.1, 6.3, 1.9, "", fc="#f2f7f0", ec="#3c7a3f")
ax.text(3.35, 4.7, "COUNTER-CLAIM MANIPULATIONS (both structures, same items)",
        ha="center", fontsize=8.2, weight="bold", color="#265428")
ax.text(3.35, 4.15, 'Authority rung:  anon ("someone") < high-schooler < grad < professor',
        ha="center", fontsize=7.8)
ax.text(3.35, 3.7, "Direction:  incorrect endorsement (asserts wrong X)  |  correct endorsement",
        ha="center", fontsize=7.8)
ax.text(3.35, 3.3, "Persona A/B (exploratory): generic ladder vs domain-matched institutional ladder",
        ha="center", fontsize=7.8)
arrow(2.45, 5.55, 2.9, 5.05); arrow(7.55, 5.55, 5.6, 5.05)

# measurement
box(7.0, 3.1, 2.9, 1.9, "MEASUREMENT\nanswer flip (behavioral)\nA–D log-probs (belief)\nLLM judge, human-validated\n(κ=0.967, main run)", fc="#f6eef7", ec="#7b4b8a", fs=7.6)
arrow(6.5, 4.05, 7.0, 4.05)

ax.text(0.2, 2.3, "Excluded: first-person control rung (a stronger, format-mismatched manipulation — analyzed separately);\n"
                  "single-turn control prompts (incoherent referent before any answer exists).",
        fontsize=7.2, style="italic", va="top")
ax.text(0.2, 1.2, "Pre-registered before any inference (ANALYSIS_PLAN.md, git 427d75a, 2026-06-29):\n"
                  "confirmatory test = authority-tier × direction interaction.",
        fontsize=7.2, va="top", weight="bold")
fig.tight_layout()
fig.savefig(os.path.join(FIGDIR, "fig9_design_schematic.png"), dpi=300)
plt.close(fig)

# ---------------- fig10: commitment penalty ----------------
CP = NUM["commitment_penalty"]
fig, ax = plt.subplots(figsize=(7.0, 3.6))
xs = range(len(MODELS))
w = 0.38
one = [CP[m]["one_turn_pct"] for m in MODELS]
twoT = [CP[m]["two_turn_pct"] for m in MODELS]
b1 = ax.bar([x - w / 2 for x in xs], one, w, label="single-turn (no commitment)", color="#c8875e", ec="black", lw=0.4)
b2 = ax.bar([x + w / 2 for x in xs], twoT, w, label="two-turn (after self-commitment)", color="#4472a8", ec="black", lw=0.4)
for x, m in zip(xs, MODELS):
    amp = CP[m]["amplification"]
    ax.annotate(f"×{amp}", (x + w / 2, CP[m]["two_turn_pct"] + 2.5),
                ha="center", fontsize=9, weight="bold")
ax.set_xticks(list(xs), [LABEL[m] for m in MODELS], fontsize=8)
ax.set_ylabel("caving rate, incorrect arm (%)")
ax.set_ylim(0, 118)
ax.legend(loc="upper center", bbox_to_anchor=(0.5, 1.02), ncol=2, fontsize=8, frameon=False)
ax.set_title("Prior self-commitment multiplies capitulation 1.9–9.3× (paired McNemar p<10⁻¹⁵, all six models)",
             fontsize=9, pad=18)
npairs = [CP[m]["n_pairs"] for m in MODELS]
ax.text(0.99, 0.02, f"identical items & authority tiers (anon–high); gated subset; n={min(npairs)}–{max(npairs)} pairs/model",
        transform=ax.transAxes, ha="right", fontsize=6.8, style="italic")
fig.tight_layout()
fig.savefig(os.path.join(FIGDIR, "fig10_commitment_penalty.png"), dpi=300)
plt.close(fig)

# ---------------- fig11: confidence doesn't protect ----------------
Q = NUM["confidence_quintiles"]["quintiles"]
fig, ax = plt.subplots(figsize=(5.4, 3.4))
xs = [q["q"] for q in Q]
ps, los, his = [], [], []
for q in Q:
    k = round(q["flip_pct"] * q["n"] / 100)
    p, lo, hi = wilson(k, q["n"])
    ps.append(100 * p); los.append(100 * (p - lo)); his.append(100 * (hi - p))
ax.errorbar(xs, ps, yerr=[los, his], fmt="o-", color="#4472a8", capsize=3, lw=1.5, ms=5)
ax.set_xticks(xs, [f"Q{q['q']}\n({q['gap_range'][0]}–{q['gap_range'][1]})" for q in Q], fontsize=7.5)
ax.set_xlabel("pre-pressure belief margin quintile (turn-1 logP(correct) − logP(X))")
ax.set_ylabel("flip rate under incorrect\nendorsement (%)")
ax.set_ylim(0, 100)
ax.axhline(ps[-1], color="#b3542e", ls=":", lw=1)
ax.annotate(f"highest-confidence quintile still flips {ps[-1]:.0f}%",
            (5, ps[-1]), xytext=(2.7, 92), fontsize=8, color="#7a3113",
            arrowprops=dict(arrowstyle="->", color="#7a3113", lw=0.9))
ax.set_title("Prior confidence does not protect (pooled, n=2,752)", fontsize=9)
fig.tight_layout()
fig.savefig(os.path.join(FIGDIR, "fig11_confidence.png"), dpi=300)
plt.close(fig)

print("wrote fig9_design_schematic.png, fig10_commitment_penalty.png, fig11_confidence.png")
